### ISSUE TITLE
Request path contains unescaped characters

### ISSUE THREAD

**Issue by drandreaskrueger** [brecke/bitbar-vpn-flag#1]
```
./IP-country-flag.10s.js 
_http_client.js:127
      throw new ERR_UNESCAPED_CHARACTERS('Request path');
      ^

TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:127:13)
    at request (https.js:303:10)
    at Object.get (https.js:307:15)
    at _request (~/.config/argos/node_modules/ipapi.co/ipapi.js:21:21)
    at Object.location (~/.config/argos/node_modules/ipapi.co/ipapi.js:83:5)
    at IncomingMessage.<anonymous> (~/.config/argos/IP-country-flag.10s.js:28:9)
    at IncomingMessage.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

**Comment by drandreaskrueger** [comment]
ah, I think I found the reason:

On the problematic IP address, https://ipapi.co/ip/ says:
{'error': True, 'reason': 'RateLimited', 'message': 'Upgrade your plan @ https://ipapi.co/'}

while on a different IP, I actually get told the IP address.
